# Définir cette configuration Compose afin de lancer l'application
# The Computer Club's Blog en production.

version: '3.8'
services:
  web_app: 
    build: .
    ports: 
      - "${HOST_APP_PORT}:8000"
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - ROCKET_ADDRESS=${ROCKET_ADDRESS}
    links:
      - "db"
    depends_on:
      db:
        condition: service_healthy
  db:
    image: postgres:16-alpine
    ports:
        - "${HOST_DB_PORT}:5432"
    environment:
      POSTGRES_DB: blog
      POSTGRES_PASSWORD: admin
      POSTGRES_USER: thomas
    healthcheck:        
      test: ["CMD-SHELL", "sh -c 'pg_isready -h localhost -U thomas -d blog'"]
      interval: 10s
      timeout: 5s
      retries: 10   
    volumes:
        - db_data:/var/lib/postgresql/data

volumes:
  db_data:
    driver: local

