# Définir cette configuration Compose afin de lancer l'application
# The Computer Club's Blog en production.

version: '3.8'
services:
  web_app: 
      build:
        context: .
        dockerfile: Dockerfile
      ports: 
        - "8000:8000"
      depends_on:
        - db
      environment:
        - .env
  db:
    image: postgres:16-alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: blog
      POSTGRES_PASSWORD: admin
      POSTGRES_USER: thomas
    volumes:
     - db_data:/var/lib/postgresql/data
  

volumes:
  db_data:
    driver: local

