# Définir cette configuration Compose afin de lancer l'application
# The Computer Club's Blog en production.

version: '3.8'
services:
  web_app: 
      build:
        context: .
        dockerfile: Dockerfile
      ports: 
        - "7000:7000"
      depends_on:
        - db
      environment:
        - DATABASE_URL=${DATABASE_URL}
        - ROCKET_ADDRESS=${ROCKET_ADDRESS}
      networks:
        network:
          ipv4_address: 10.5.0.5
  db:
    image: postgres:16-alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: blog
      POSTGRES_PASSWORD: admin
      POSTGRES_USER: thomas
    networks:
        network:
          ipv4_address: 10.5.0.4
    volumes:
     - db_data:/var/lib/postgresql/data

networks:
  network:
    driver: bridge
    ipam:
      config:
        - subnet: 10.5.0.0/16
          gateway: 10.5.0.1

volumes:
  db_data:
    driver: local

