# Définir cette configuration Compose afin de lancer l'application
# Grilli en production.
version: '3.8'

services:
  nginx:
    image: nginx:latest
    container_name: resto-grilli
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - .:/var/www/html
    depends_on:
      - php

  php:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: php-fpm
    volumes:
      - .:/var/www/html
    environment:
      - .env