# Définir cette configuration Compose afin de lancer l'application
# Grilli en production.
version: '3.8'

services:
  nginx:
    image: nginx:alpine
    container_name: resto-grilli-nginx
    ports:
      - "${PORT_NGINX}:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - .:/var/www/html
    depends_on:
      - php

  php:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: resto-grilli-php
    volumes:
      - .:/var/www/html
    environment:
      - .env