# Définir cette configuration Compose afin de lancer l'application
# Grilli en production.
version: '3.8'

services:
  nginx:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: resto-grilli
    ports:
      - "80:80"
    environment:
      - APP_ENV=prod