# Définir cette configuration Compose afin de lancer l'application
# Make Me Watch en production.


version: '3.8'

services:
  # Définition du service serveur (API)
  server:
    build:
      context: ./server
      dockerfile: ./Dockerfile
    ports:
      - "3000:${API_PORT}"
    restart: unless-stopped

  # Définition du service client (SPA)
  client:
    build:
      context: ./client
      dockerfile: ./Dockerfile
      args:
        API_BASE_URL: ${API_BASE_URL}
    ports:
      - "80:${CLIENT_PORT}"
    environment:
      - API_BASE_URL=${API_BASE_URL}
    depends_on:
      - server
    restart: unless-stopped